### ISSUE TITLE
#3738 [a+] Captcha for a+ contact page and registration form

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/adhocracy-plus#1159]
**URL:** https://aplus-dev.liqd.net/accounts/signup/?next=/
**Comment/Question:** 
CAPTCHA is working fine but there is a light blue selection stroke around the 30 and below the 2 that seems a bit off, maybe leaving just the black one around the number is already enough. 

![Screenshot 2021-03-10 at 17 59 59](https://user-images.githubusercontent.com/59610786/110667637-bed5ed80-81ca-11eb-81ce-224555576cc5.png)

**Comment by phillimorland** [comment]
@mcastro-lqd can't reproduce, what browser/screen size was this on?

**Comment by mcastro-lqd** [comment]
@phillimorland Safari Version 14.0.3 (16610.4.3.1.7) - both Mobile + Desktop

**Comment by lthueer** [comment]
@phillimorland @fuzzylogic2000 this issue is still there on Safari and Iphone for the text and image mode (see screenshots below)

![Bildschirmfoto 2021-05-17 um 15 41 11](https://user-images.githubusercontent.com/36957474/118500498-1db66680-b728-11eb-9327-80094147909c.png)

![Bildschirmfoto 2021-05-17 um 15 41 16](https://user-images.githubusercontent.com/36957474/118500510-21e28400-b728-11eb-9d88-72e6c0b2f99a.png)
