### ISSUE TITLE
#3874 private projects email not translated

### ISSUE THREAD

**Issue by lthueer** [liqd/adhocracy-plus#1253]
**URL:** 
**user:** 
**expected behaviour:** emails are either in German or English
**behaviour:** for the private project link email the English and German language becomes mixed up
**important screensize:**
**device & browser:** 
**Comment/Question:** 

- How about the translations for the other languages from Transifex? Should it be part of the acceptance criteria? It's not in there because I thought you would push all new strings to transifex anyways before the next release

![Bildschirmfoto 2021-05-05 um 14 43 52](https://user-images.githubusercontent.com/36957474/117143127-c7a10500-adb0-11eb-8cd9-4c0b0d25c5cf.png)

**Comment by fuzzylogic2000** [comment]
Yes, here in a+, where we use transifex, we can't have the translation in the acceptance criteria, because we (meaning the devs) are not doing them. The translations will be added by the translators later, when we have finished all stories and have pushed the strings to transifex, then we will pull the translated strings before we release.
So, no need to test if the translations are there. If you want to know that the e-mails are sent in the right language (once the translations are there), you can normally have a look into the email-footer. (Or here you can also see at "Guten Tag" that the email is sent in the right language.)
So, only wording issues you need to add as an issue is if the English wording is wrong. :)

**Comment by fuzzylogic2000** [comment]
Right, and the mix of the languages is because some strings that we use in multiple e-mails (Hello and the footer for example) are already trabnslated while the new ones aren't.

**Comment by lthueer** [comment]
Cool, thank's for the small excursus. Then I got it (almost) right ;)
