### ISSUE TITLE
in multi module project, link of comment on poll links to project page instead of detail page

### ISSUE THREAD

**Issue by Rineee** [liqd/adhocracy-plus#1361]
**URL:** https://aplus-dev.liqd.net/rines-test-orga/projects/test-projekt/?comment=345 
**user:** 
**expected behaviour:** 
**behaviour:** 
**important screensize:**
**device & browser:** 
**Comment/Question:** It seems to work for other modules, eg https://aplus-dev.liqd.net/rines-test-orga/ideas/2020-00205/?comment=214
same in mB https://github.com/liqd/a4-meinberlin/issues/3692

Screenshot?

**Comment by sabinammm** [comment]
I tested this and unless I'm misunderstanding the issue, it seems to work fine: 
i.e. when I have lots of comments and comments on comments underneath a poll, I can click on "share" and this link will take me directly to the exact comment of the share-button. 
The links seem to be correct, and do not lead to the project page. 
Can you let me know if I'm misunderstanding @lthueer please?

**Comment by lthueer** [comment]
@sabinammm thank you for taking care of it! To me it seems fixed, all links in different modules work for the comments, and also the excel export works. I am closing this issue now!

**Comment by sabinammm** [comment]
Hmmm, well I don't know what I may be doing wrong, but when I export a Poll on Dev, I get links that look e.g. like this:
https://aplus-dev.liqd.net/rines-test-orga/projects/test-projekt/?comment=345
even though the link to the comment is supposed to be:
https://aplus-dev.liqd.net/rines-test-orga/projects/module/umfrage-11/?comment=345
The link that shows up in the excel-list, then links to the project page.

**Comment by lthueer** [comment]
@sabinammm I am not sure either. It seems to work for other poll module exports: https://aplus-dev.liqd.net/teststadt-luca/projects/poll-test/
I think we can close it for now anyways as the poll module and export will also be changed with the next a+ sprint, so it might be alright then! What do you think?

**Comment by fuzzylogic2000** [comment]
@sabinammm @lthueer Yes, this will be fixed when we use the polls from a4. So, I close it again?!?
[And for explanation: for these things the `get_absolute_url()` of the `Poll` is used, which didn't know if it was meant to show the module or project view and with or without timeline info and always showed the module detail.
fixed in 
https://github.com/liqd/adhocracy4/commit/3c381ce18ab72e847dd68782f20828bfd3eb511f
which was using
https://github.com/liqd/adhocracy4/blob/bd3d5beed4cf037157fa9be3fa1f8df832497eee/adhocracy4/modules/models.py#L94
and is now using
https://github.com/liqd/adhocracy4/blob/bd3d5beed4cf037157fa9be3fa1f8df832497eee/adhocracy4/modules/models.py#L98
]
Or no, now I am also not sure if this is fixed here or only in the reports. What about putting it into the release milestone as a reminder and check when the poll stuff is done?

**Comment by sabinammm** [comment]
It works now:)

**Comment by lthueer** [comment]
cool, thank you @sabinammm
