### ISSUE TITLE
cannot vote proposals up or down in spatial brainstorming 

### ISSUE THREAD

**Issue by Amelie-liqd** [liqd/adhocracy-plus#137]
**URL:** https://adhocracy.plus/test/projects/module/brainstorming-mit-karte-2/
https://adhocracy.plus/test/mapideas/2019-00402/
**user:** all
**expected behaviour:** When I see a proposal on a map, I can see how many comments, up and down votes that proposal has. I can click on the project and vote it up if I like it. 
**behaviour:** When clicking on a proposal on a map, I cannot vote it up or down. 
**device & browser:** macbook air & firefox 

![Bildschirmfoto 2019-12-06 um 12 45 27](https://user-images.githubusercontent.com/57798416/70321028-82c51780-1826-11ea-9b88-b6a7fd35801a.png)

**Comment by CarolingerSeilchenspringer** [comment]
same is true for the list view and I think we should change that. I watched someone young not knowing our software clicking on the idea in the list because this is what people do using Instagram etc. Alternatively, if we want people to read the idea before voting, we should change the design showing that this is a statistic and no call for action.

**Comment by phillimorland** [comment]
NOTE: voting works locally?!
