### ISSUE TITLE
Do we want to stick to reference numbers from meinberlin

### ISSUE THREAD

**Issue by MagdaN** [liqd/adhocracy-plus#161]
**URL:** e.g here: https://aplus-dev.liqd.net/buro-fur-vielfalt/budgeting/2018-00062/
**user:** participants
**expected behaviour:** the url contains slug or id
**behaviour:** the url included a strange number (here: 2018-00062)
**important screensize:**
**device & browser:** 
**Comment/Question:** This number was once added to meinberlin as this was a requirement from the administration. @rittermo @fredewe Do we want this on this platform as well?

**Comment by phillimorland** [comment]
NOTE: we have stopped displaying them for dashboard added content e.g. debate subjects and topic prios

**Comment by fuzzylogic2000** [comment]
@fredewe @lthueer Do we still want the reference numbers or should we replace them by normal PKs (that's basically the reference number without the year).

**Comment by fredewe** [comment]
@fuzzylogic2000 i do not feel that i can decide that because i can't estimate the advantages and disadvantages of having/not having the numbers.

**Comment by fuzzylogic2000** [comment]
We had to add the reference numbers to mB to make it look more "administrative". The downside of having them is more code to look after. The upside of keeping them is no work to put it, because it's already like that.
@fredewe I think, we can close this issue then? Or should it stay as a reminder and with low prio?
