### ISSUE TITLE
Error message incomplete for unsaved mandatory fields in Safari

### ISSUE THREAD

**Issue by lthueer** [liqd/adhocracy-plus#1613]
**URL:** https://aplus-dev.liqd.net/teststadt-luca/dashboard/modules/ideenwettbewerb-24/module_basic/
**user:** initiator
**expected behaviour:** browser error message indicates what something is missing or has not being saved
**behaviour:** error message same as in firefox, chrome
**important screensize:**
**device & browser:** Safari
**Comment/Question:** Maybe adapt/specify the wording here?

Current wording: 
"This page is asking you to confirm that you want to leave — information you’ve entered may not be saved."
"Diese Seite bittet um Bestätigung, dass Sie die Seite verlassen möchten - von Ihnen eingegebene Informationen werden unter Umständen nicht gespeichert."

![Bildschirmfoto 2021-12-21 um 10 56 27](https://user-images.githubusercontent.com/36957474/146910209-b0fbac6a-ad55-41c6-a57a-b0bcdc7ff097.png)

**Comment by fuzzylogic2000** [comment]
This is not an error message, but a warning and I think it is the same wording for all browsers. It looks different because we use the browsers built-in warning thingies.
![Screenshot from 2022-01-05 14-38-50](https://user-images.githubusercontent.com/8178179/148226881-cd7fbe5c-b149-4c99-8c7d-b346f7be9d81.png)
If that needs to be changed it should be a story, I think.

**Comment by lthueer** [comment]
@fuzzylogic2000 alright, thanks for clarification. Closing this issue and taking it to the a+ backlog - if needed.
