### ISSUE TITLE
Dashboard: invite moderators/participants (private projects) styling 

### ISSUE THREAD

**Issue by lthueer** [liqd/adhocracy-plus#1660]
https://aplus-hafencity-dev.liqd.net/dashboard/projects/alle-module-testen/moderators/
Browser: Firefox 96, Chrome 97

![Bildschirmfoto 2022-01-17 um 17 47 40](https://user-images.githubusercontent.com/36957474/149809351-a2690fec-0e2d-4d99-a477-febeaf667c13.png)

Notes:
Connected to #1657?

**Comment by fredewe** [comment]
Seems to be the same as this one: https://github.com/liqd/adhocracy-plus/issues/1657

**Comment by lthueer** [comment]
@khamui in firefox it looks good, however, in safari it's still there
![Bildschirm­foto 2022-12-06 um 13 02 34](https://user-images.githubusercontent.com/36957474/205906850-6473f946-8179-481a-84b6-74d5b34e6bdf.png)

**Comment by lthueer** [comment]
@khamui also I've realised that the phases look a bit off, if that's connected to this issue. If not, i put it in another issue. Tested in chrom, ff and safari
![Bildschirm­foto 2022-12-06 um 13 14 59](https://user-images.githubusercontent.com/36957474/205910190-0d71f64c-364f-4020-bbe1-1da9b6e17702.png)

**Comment by khamui** [comment]
@lthueer the second issue with the phases is not related. Should be solved differently and therefore better to put it into another issue.

regarding the original issue, after updating safari to version 16.1 I could replicate the issue you mentioned. Weirdly after a while it does not appear anymore (after refreshing the website). Still not sure what the cause is, but somehow it appears intermittently. Shall I try more, or do you think this is quite an edge case, so we could leave for now? I spent quite a bit of time already.

**Comment by lthueer** [comment]
@khamui i think it's fine as it's only in Safari! Closing the issue now. Thank youuu! I put the other issue into the milestone as this appears everywhere
