### ISSUE TITLE
a+ Moderator invite mail: Scaling of image

### ISSUE THREAD

**Issue by fredewe** [liqd/adhocracy-plus#1666]
**URL:** 
**user:** invited moderator
**expected behaviour:**
**behaviour:** The image is too big and overlaps the text
**important screensize:**
**device & browser:** MacOS 11.6, apple Mail
**Comment/Question:** 

This is how it looks:
![Bildschirmfoto 2022-01-18 um 11 59 34](https://user-images.githubusercontent.com/5470479/149925984-14d574c0-9f70-4efc-906f-1188494f1789.png)

This is how it should look, right?
![Bildschirmfoto 2022-01-18 um 12 03 28](https://user-images.githubusercontent.com/5470479/149926064-7e5db768-aba6-4d37-a5cc-19e458722cbf.jpg)

**Comment by khamui** [comment]
after investigating I could replicate this issue in Apple Mail. But not sure how to debug this (since it is working in Thunderbird for instance).

In any case it has to do with the very high resoluted logo image (over 2500 pixels). My suggestion would be to set a limit for the resolution when uploading (currently it checks for 1:1 aspect ratio already). Not only this would -probably- fix the issue above, but also we would avoid large images to be uploaded as logos and avoid download times for the receivers?

what do you think @fredewe? Would we be able to check the resolution before uploading @fuzzylogic2000?

**Comment by fredewe** [comment]
@khamui thanks for investigating! That solution would be fine for me and sounds great. As this issue is apple mail only i would not put too much effort in it. But shorter download time is always great. ;)

**Comment by fuzzylogic2000** [comment]
Yes, we can do that. But what should happen to the old images that are too big? Can we remove them? And how much time should we spent on that? Can you please prioritize @fredewe ?

**Comment by fuzzylogic2000** [comment]
Ok, no, Kommando back! I think @khamui already added that validation and as it's not in the model field, but an extra validation, it should be fine and we can keep the old images. :)
@fredewe But that means, you cannot test that with your existing logo, because that problem will stay. It only cannot happen again for new organisations when they add a logo.

**Comment by fredewe** [comment]
Sounds good to just do it for new logos and keep the old logos as they are.

**Comment by fredewe** [comment]
Can we close this one here https://github.com/liqd/adhocracy-plus/issues/1770 ? It seems to be the same.
