### ISSUE TITLE
long title on tile for module: line break within word  

### ISSUE THREAD

**Issue by maxliqd** [liqd/adhocracy-plus#1780]
**URL:** https://aplus-stage.liqd.net/base/projects/online-konsultation-geschaftsordnung/
**user:** initiator filling in verbal information
**expected behaviour:** Everything that I write looks nice when handed out, no line breaks within words.
**behaviour:** Long, but used word like Geschäftsordnung have a line break within the word
**important screensize:** Desktop
**device & browser:** Mac firefox, chrome
**Comment/Question:** 

Screenshot?

![grafik](https://user-images.githubusercontent.com/94360651/162430471-97d61209-d76c-4c4d-bce1-21d8e633d5ed.png)

**Comment by fuzzylogic2000** [comment]
There is not really anything, we can do here when we keep the design like that.
The options would be:
1. make the font smaller
2. make the tile bigger (3 tiles in one row instead of 4)
3. make the tile bigger for smallish screens, but not big ones

@lthueer @fredewe @mcastro-lqd Please decide if and how we need to change that.

**Comment by mcastro-lqd** [comment]
@maxliqd @fuzzylogic2000 I've already thought about that and I might still have the screen I made ages ago. There is no way to put the German hyphenation in the code, right?  I would also then make 3 tiles instead of 4 and the font a bit smaller cause German words are always long and people won't write in different ways to make it look better.

**Comment by maxliqd** [comment]
@lthueer @fredewe Just tagging you here as this is more of an issue/ design decision for the two of you.

**Comment by fredewe** [comment]
I would go with what @mcastro-lqd proposed. Thanks
