### ISSUE TITLE
checkboxes: text layout looks off

### ISSUE THREAD

**Issue by lthueer** [liqd/adhocracy-plus#1980]
**URL:** https://aplus-stage.liqd.net/testorga-luca/projects/erf/?initialSlide=1
**user:** 
**expected behaviour:** the second sentence follows after the first (see screenshot) how it is in the poll module
**behaviour:** weird line break and layout looks off
**important screensize:**
**device & browser:** 
**Comment/Question:** for the poll module it looks fine. This is only for comments and within the debate module. In English the checkbox text looks fine, it's just the other languages when sentences are longer. 

1) comments + debate module
<img width="1097" alt="Bildschirmfoto 2022-07-18 um 13 12 26" src="https://user-images.githubusercontent.com/36957474/179499981-a32879cc-5576-42ae-b2d2-003fda1a1683.png">

2) When creating an idea the text looks also different. Also the checkbox for copyright has a weird line distance
<img width="989" alt="Bildschirmfoto 2022-07-18 um 13 24 57" src="https://user-images.githubusercontent.com/36957474/179501984-795a60b5-e490-4a55-bbf4-d6626bb9bc00.png">

**Comment by khamui** [comment]
as @lthueer mentioned in the other issue, this seems to be fixed already by:
https://github.com/liqd/adhocracy-plus/pull/2125

**Comment by khamui** [comment]
after checking the first described issue, I think the first paragraph is the `terms of use` and the second is the `help text`. Both are defined separately and can't be really merged together.

In case of the poll those do not break into second lines because of the button, which looks less awkward. On mobile it will look similar to the idea case.

We could make the help text `italic`, so there is a clear difference. I saw the italic help text somewhere already. not sure if it is on aplus though. What do you think @lthueer ?
