### ISSUE TITLE
stage: translations missing

### ISSUE THREAD

**Issue by lthueer** [liqd/adhocracy-plus#2221]
**URL:** https://aplus-stage.liqd.net/testorga-luca/dashboard/communication/content/create/sadf-3/format/1/
**user:** 
**expected behaviour:** all translations are there
**behaviour:** translations are missing
**important screensize:**
**device & browser:** 
**Comment/Question:** 

- dev & stage
- translations for module type are there in dashboard (only missing on tile)
- translation strings are on Transifex but not on a+

helptexts fpr sharepics
<img width="878" alt="Bildschirm­foto 2023-01-11 um 15 28 38" src="https://user-images.githubusercontent.com/36957474/211834057-a25d723a-a748-4a6a-ad11-3b09c7714e29.png">

type of module not translated
<img width="944" alt="Bildschirm­foto 2023-01-11 um 15 28 11" src="https://user-images.githubusercontent.com/36957474/211832308-b5bff7c9-0118-4235-b370-7f703e00e9df.png">

**Comment by fuzzylogic2000** [comment]
For the first one with the form, I could only make it work when I removed the variables from the strings. So, that would mean new strings. I propose:
"This title will be displayed as a header. Max. chars: "
"This description will be displayed below the title. It should briefly state the goal of the project. Max. chars.: "
"The picture will be displayed in the sharepic. Allowed file formats are png, jpeg, gif. The file size should be max. 5 MB. Min. pixels width * height: "
Would that be alright, if we don't find a better way?

**Comment by fuzzylogic2000** [comment]
Yes, that would still happen. The sizes would be added to the end of the string. Like
"The picture will be displayed in the sharepic. Allowed file formats are png, jpeg, gif. The file size should be max. 5 MB. Min. pixels width * height: 1080 * 760"
But they are not part of the string anymore, but come after it. So, it's actually sth., that we try not to do, because it might not be possible to do it like that in other languages. but here, I just didn't find another way.

**Comment by lthueer** [comment]
cool! Sounds good to me
