### ISSUE TITLE
Homepage does not show image on a new installation

### ISSUE THREAD

**Issue by erelsgl** [liqd/adhocracy-plus#2728]
When I clone this repo and install adhocracy-plus on a new server, the homepage looks differently than in the https://adhocracy.plus/ site. In particular, the image is not shown; instead, I see only a gray background.
I thought that maybe the image is inserted through the wagtail interface, so it is saved only in the database and not in the github repo. Is this correct? 
Should I manually change the homepage appearance through the wagtail interface whenever I install adhocracyplus on a new server?
Alternatively, is there a way to keep the changes I make through wagtail to the github repo?

**Comment by goapunk** [comment]
Hi @erelsgl, yes that's correct, you have to customize the landing page manually. I'm not sure if there's an automated way for new installations but if you always want the exact same **static/non-wagtail** landing page you could just create a normal django template (+view) and use that instead of the wagtail landing page.
