### ISSUE TITLE
"Show more" of shortened comments is not displaying more

### ISSUE THREAD

**Issue by hmkay** [liqd/adhocracy-plus#286]
**URL:** https://aplus-dev.liqd.net/teststadt/subjects/2020-00156/
**user:** admin
**expected behaviour:** If I click on "show more" the whole comment is shown
**behaviour:** The comment is still not shown completely, but he naming changes to "show less"
**important screensize:** desktop and mobile
**device & browser:** macOS Mojave 10.14.6, Firefox 72.0.2 (64-Bit)
**Comment/Question:** 

![Bildschirmfoto 2020-02-04 um 16 00 12](https://user-images.githubusercontent.com/30862422/73758011-5b2cf580-476a-11ea-9e90-faa4cb99a5e0.png)

**Comment by phillimorland** [comment]
@hmkay cannot reproduce with normal word structure up to 2000, do we want to chase an issue that only exists if you have a single 400 charecture word?

**Comment by hmkay** [comment]
@phillimorland ah, I guess this is a misunderstanding, it is about the "read more" button. If I click it, nothing happens...? Or do you mean you couldn´t reproduce that neither?

**Comment by phillimorland** [comment]
@hmkay the reason nothing happens is because you have tested with 1 long word, not multiple words, if you add multiple words then the read more tag works fine however if you add one 400 letter word it doesn't but my question is, do we care? if someone is adding a 400 letter word then they aren't using it properly anyway

**Comment by hmkay** [comment]
@phillimorland hahahahahaha xD ok. no we don´t care. Thanks for clarification :D

**Comment by phillimorland** [comment]
cool! :)
