### ISSUE TITLE
Deleting a comment does not delete or change the activity

### ISSUE THREAD

**Issue by rmader** [liqd/adhocracy-plus#313]
So the activity might still be shown, even if the comment does not show the author any more.

**Comment by phillimorland** [comment]
@rmader do you mean in the activity log of the user or in the comment list? also do we want to remove the activity, it was still something that was done? what do you guys think? @hmkay @fuzzylogic2000 @fredewe

**Comment by fuzzylogic2000** [comment]
Yes, it is still in the db-table for the activies, so shows up wherever we use them.
I think, we need to remove the wording of the comment. But don't know about the rest. And we do say deleted author or something like that in the comment. The activity also shouldn't show up in the user's profile, I think.

**Comment by hmkay** [comment]
I think I am confused. Are you talking about the activity feed in the profile? Of what I understood I would support @fuzzylogic2000

**Comment by fuzzylogic2000** [comment]
So, to do:

- [ ] check if the text of a deleted comment is still accessible in the activity
- [ ] check what happens when a comment is updated (and if accessible there if deleted afterwards)
- [ ] also change the wording/delete the wording in activity if that's the case

**Comment by sabinammm** [comment]
@fuzzylogic2000 Since I'm working on the comments, I'm looking at this. The act of deleting a comment isn't documented in the activities. Comments that have been deleted are still visible, but marked as deleted. The comments that have been deleted are thus documented as "added" in the activity of those who made them, but not those who deleted them. Should the act of deleting be added?

**Comment by fuzzylogic2000** [comment]
@sabinammm Yes, that's the question!
And that is something @fredewe and @lthueer have to answer, but also the other projects which show actions. So also @CarolingerSeilchenspringer @hmkay  and @hello-kathi .
So, currently when a comment is added, we also add an activity that the comment was added. When a comment is deleted by either the author or a moderator, we do not really delete the comment, but change the comment text and do not display the author in the comment anymore. So, the action still displays the comment author, even if the comment is "deleted".
For the ideas, when an idea is deleted, the action is also deleted. 
While we still need to discuss what to do with the offending comments (and ideas) for KOSMO and when we have a moderation dashboard, **I think the solution here to make it inline with the ideas would be to delete the action when a comment is "deleted".**
And then we can still think about adding a story to tackle the whole behaviour if we want to also have a delete action and keep the add and update actions for ideas and comments.

**Comment by hello-kathi** [comment]
@fuzzylogic2000 @CarolingerSeilchenspringer @sabinammm @fredewe @lthueer @hmkay 
Does it matter if the action to the comment is deleted too? For me it is hard to imagine of the outcome. Does that mean, if we are deleting the comment and the action, it will not show anymore that there was a comment and it is deleted now? Like it is now that the action shows user Name and comment deleted?

**Comment by fuzzylogic2000** [comment]
@hello-kathi The action have a pointer to what they refer to. If the thing they point to is really deleted, then the action currently also is. That is the case for ideas. When an idea is deleted, so are all actions (and comments and so on) pointing to that idea.
For comments this doesn't work because when a user or moderator clicks the "delete" button we do not really delete the comment, but only change it's text and behaviour in the comment display. We could delete the action without changing the comment, because only the action knows which comment it belongs to, but not the other way round. 
And that is what I was proposing: the behaviour of the comments stays the same, but the action is deleted when the delete-comment-button is clicked.
Does that make sense?

**Comment by hello-kathi** [comment]
@fuzzylogic2000 I think I got it now :) OK I think I go with your suggestion :D

**Comment by fredewe** [comment]
sounds good for me!

**Comment by hmkay** [comment]
Thank you for thinking about this! I am also in, go for it =)

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 I also go along with what you say. Thanks!

**Comment by fuzzylogic2000** [comment]
@Rineee You did fix that in a4, right?

**Comment by Rineee** [comment]
I did fix it here https://github.com/liqd/adhocracy4/pull/881, yes!
