### ISSUE TITLE
a+ Module status bar - User testing

### ISSUE THREAD

**Issue by phillimorland** [liqd/adhocracy-plus#370]
All the projects on https://stage.enquetebeteiligung.de run for 39 days, but the progress bars have different lengths

**Comment by fuzzylogic2000** [comment]
In this case it was because, the start dates where set differently. So in this very special case it's fixed. But I still stink it's confusing, when it just says how many days are left and displays a status bar where it's not clear what that means.
Can we put something like "9 days of 3 weeks" left? What do you think, @mcastro-lqd ?

**Comment by fuzzylogic2000** [comment]
@hmkay We can discuss our ideas how to do it differently here!

**Comment by hmkay** [comment]
I think it would be cool to have an indication of the status bar rather on how long the Participation is still on. Something like:
Small bit filled: participation longer than 3 months
Quater filled: participation is longer than 1month, shorter than 3 months
half filled: 3 weeks - 1 month
3/4 filled: 10 days - 3 weeks
4/5 filled: 5-10 days 

...and then getting closer on the last 5 days? I don´t really know, maybe @mcastro-lqd has an idea?

**Comment by phillimorland** [comment]
@hmkay @fuzzylogic2000 @mcastro-lqd I think the idea of saying "9 days of 3 weeks left" is the clearest suggestion so far for the user

**Comment by hmkay** [comment]
@phillimorland that sounds good. What do you think, @mcastro-lqd and @fredewe ?

**Comment by mcastro-lqd** [comment]
Sorry, I didn't see this message before. 

@hmkay @fredewe I'm fine with @phillimorland `s idea, but most of the big platforms like crowd fundings(e.g. Kickstarter, Indiegogo), etc. use "tage verbleibend"/"days remaining". In my opinion, I still think it's better to keep it simple. The idea of having a progress bar already shows exactly that, otherwise, we would just write the remaining days.

**Comment by fredewe** [comment]
also fine with it!

**Comment by lthueer** [comment]
Closing this as it seems solved with Marcelo's comment to keep it as it is
