### ISSUE TITLE
enq Notification email only has a bundestag logo and no platform name - User testing

### ISSUE THREAD

**Issue by phillimorland** [liqd/adhocracy-plus#379]

**Comment by phillimorland** [comment]
@hmkay wording

**Comment by phillimorland** [comment]
@hmkay I need this as soon as possible, sorry!

**Comment by hmkay** [comment]
Wording:

Reaktion auf Ihren Beitrag auf enquetebeteiligung.de

Hallo *Benutzer*innenname*, 

*anderer Benutzer*innenname* hat Ihren Beitrag kommentiert: 

"*QUOTE*"

Möchten Sie antworten?

BUTTON: Jetzt antworten! (or: Jetzt mitmachen!)

---

Question: Can we easily change the button? Otherwise, I´d think about a different wording for "Möchten Sie antworten?"

**Comment by fredewe** [comment]
It is fine for me like that.
