### ISSUE TITLE
a+ Styling of project list when odd number of projects - user testing

### ISSUE THREAD

**Issue by phillimorland** [liqd/adhocracy-plus#389]
**URL:** https://aplus-dev.liqd.net/teststadt/
**expected behaviour:** if there is an odd number of projects, the list looks a little unfinised

Screenshot?

**Comment by fuzzylogic2000** [comment]
@mcastro-lqd Any idea how to improve?

**Comment by fuzzylogic2000** [comment]
We either need the decision what to do about this or the decision that this is fine like it is now and can be closed.

(Extra info: there is an extra style for a single project of an organisation. Can we do something with that? Would be a bit complicated, though, because we have different lists for active, future and past projects. Maybe we can also split these lists and give them separate headlines and do sth. about odd numbers in any of these lists?)

**Comment by mcastro-lqd** [comment]
@fuzzylogic2000 @phillimorland I think we should put a Show More button after displaying 16 projects ungef. cause since most of the projects are finished, most of the scrolling in the end is useless. Would that be ok fo you?

**Comment by fuzzylogic2000** [comment]
Yes! Good idea! Maybe not the easiest solution, though. :) Oh, actually because of the three lists it's quite hard to do and would need quite a refactor. But yes, I guess that's fine and can wait until we have time.

**Comment by fuzzylogic2000** [comment]
@fredewe @lthueer Can this become a story? Then we can shorten the list and show a "Show more" button and also do somwthing about an odd number below 16 projects.

**Comment by lthueer** [comment]
@fuzzylogic2000 @phillimorland I like the idea and take it as a story to the a+ backlog. @fredewe it's here: https://taiga.liqd.net/project/liqd-liquid-product/us/238?no-milestone=1
