### ISSUE TITLE
Moderation request in English?

### ISSUE THREAD

**Issue by hmkay** [liqd/adhocracy-plus#432]
**URL:** https://adhocracy.plus/igbce-workshop/subjects/2020-00655/
**user:** moderator

**Comment/Question:** I got a moderation request in English, even though everything was German before...Could you check that?

**Comment by fuzzylogic2000** [comment]
Well, the site-wide default language is English (we just changed that back because otherwise it was messing with the translations). If the emails don't know the email or user it is send to and can't look up the language it will be send in the default language. So, first question: your moderator-user has the language set to German? If yes, more questions:
How important is this? How much time should we invest?
Should all Emails be sent in German when the language of the user is not known? @fredewe

**Comment by fredewe** [comment]
I'd say yes to that. German when the language is not known. What would you say @hmkay ?

**Comment by hmkay** [comment]
Sounds good, at least at the moment as all projects so far are German! If we get superduperinternational, maybe then we need to change it.

**Comment by fuzzylogic2000** [comment]
fixed by #473
