### ISSUE TITLE
IG BCE: Get rid of Spendenbanner in Datenschutz

### ISSUE THREAD

**Issue by hmkay** [liqd/adhocracy-plus#463]
**URL:** https://adhocracy.plus/info/ig-bce-datenschutz/

Please delete Spendenbanner. Or tell me how to do it on non-related pages =) Thaaanks!

**Comment by fuzzylogic2000** [comment]
Currently you can't on not organisation-related pages. That was possible for enquete because that's an entirely different platform. For the redirects I guess it would be cool to implement, but that needs more development and should be a user story.
P.S.: It's also showing on the registration/login/user profile and all non-related pages. :(
