### ISSUE TITLE
#3328: Newsletter not sending

### ISSUE THREAD

**Issue by lthueer** [liqd/adhocracy-plus#830]
**URL:** https://aplus-dev.liqd.net/teststadt-luca/dashboard/newsletters/create/
**user:** all
**expected behaviour:** send newsletter to participants and users that follow a project
**behaviour:** newsletter is not sent; And inviting participants with other than liqd.net address do not arrive
**important screensize:** 
**device & browser:** 
**Comment/Question:** 
Due to the behaviour above, it was not possible to test story #3328 with regard to the default language settings

**Comment by fuzzylogic2000** [comment]
@lthueer Please don't assign me to issues. Thanks!

**Comment by fuzzylogic2000** [comment]
@lthueer Can you please say which project you wrote the newsletter for, as who you were logged in when you did and also who should have gotten the newsletter, but didn't?

**Comment by lthueer** [comment]
@fuzzylogic2000 I will not assign you anymore. Promised! The project is called "Newsletter test" in the organisation "Teststadt Luca", I was logged in as an initiator (lthueer+initiator) and the receivers were: lthueer+000 & lthueer+me

**Comment by phillimorland** [comment]
@lthueer the 'And inviting participants with other than liqd.net address do not arrive' shouldn't work on dev, it will only send emails to @liqd emails, can you test on stage and let us know if this is still a problem?

**Comment by lthueer** [comment]
@phillimorland it seems to be the same on stage. So maybe the same thing? It works on prod though.

**Comment by phillimorland** [comment]
@lthueer yeah we should have that in the testing guidlines maybe, would help with confusion! but i thought we only had that on dev, @rmader do we also have the non liqd email addresses blocked on stage too?

**Comment by Rineee** [comment]
@lthueer In order to receive newsletters, the user has to follow the project and has to have checked the box 'Ich möchte weitere Informationen erhalten./I would like to receive further information.' in the profile settings.
I checked your project 'Newsletter test', it has 2 follows, only one of them active: l.thueer@liqd.net, but this user doesn't have newsletters activated...
So, to test again, you have to create follows for the users you want to receive newsletters for (either by clicking directly the 'follow' on the project page or I think by adding them as moderators/participants or just by commenting or adding sth in the project) and make sure these users get newsletters.
Does that work?

**Comment by lthueer** [comment]
@Rineee alright, that was it! It works properly. There is really a lot to think about but now I got it and know it for the next time! :)

**Comment by Rineee** [comment]
Yes, thats true, its a bit complicated.. but cool that it works now, so will close this issue!
