### ISSUE TITLE
denied access to semi-private project starting in future

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/adhocracy-plus#901]
**URL:** https://aplus-dev.liqd.net/liqd-tests/
**user:** both invited & registered user and ununivited & unregistered users
**expected behaviour:** clicking on the project tile opens the project
**behaviour:** I get a 403 (invited user) or the log-in-form (uninvited user)
**important screensize:**
**device & browser:** 
**Comment/Question:** this is only when project start is in the future!!

Screenshot?

**Comment by Rineee** [comment]
Here is another example of it: https://aplus-dev.liqd.net/rines-test-orga/

**Comment by Rineee** [comment]
So I found out that this has nothing to do with semi-public projects, but is a bug that must have been there all the time, haha.. 
It is the same for public projects and is caused by [this line](https://github.com/liqd/adhocracy-plus/blob/08a67a7494f1c688a8ade8738d0b5911691755b7/apps/documents/rules.py#L10).

I dont know why this rule was defined like this in the first place, so wasnt sure how to fix it :grimacing: But I guess @fuzzylogic2000 or @rmader will :)

**Comment by fuzzylogic2000** [comment]
@Rineee Oh, yes, I can remember that I have seen that! It was to make sure, that documents and polls can only be viewed when they are not being changed anymore. I think, I already removed it from the topic prios. As the modules can now be added to or removed from the project, I think, this rule doesn't make sense anymore. Just the polls do look a bit weird, when they are shown before the phase starts. I think, it is still an improvement from a 403?

**Comment by fuzzylogic2000** [comment]
@carolinger This issue was quite an old one and had nothing to do with the semi-private projects. It's there for every document and poll. (And should also be an issue in mB.) Even though, it looks a bit weird for the polls, I think we should remove this rule and make them viewable also prior to the phase? I will open an PR fixing this.

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 it has already been changed on meinBerlin so I would also agree to it (nobody has ever complained there).
